# Generated by Django 2.2.3 on 2019-07-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='encryption',
            field=models.CharField(max_length=10),
        ),
    ]
