# Generated by Django 2.2.3 on 2019-07-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190705_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='uid',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
